#!/bin/bash

git add .

read -p "Commit message: " commit_message

if [ -z "$commit_message" ]; then
  echo "No commit message!"
  exit 1
fi

if git diff --cached --quiet; then
  echo "Nothing to commit!"
  exit 1
fi

git commit -m "$commit_message"
git push origin main

echo "Successful commit."
